-- DCL :: Transaction Control Language ::
-- São usadas para gerenciar as mudanças feitas por instruções DML. Permite que as declarações sejam agrupadas de forma ordenada e lógica.
-- Principais comandos:
    - BEGIN TRANSACTION -- Inicia uma transação
    - COMMIT -- salvar o trabalho feito
    - SAVE TRANSACTION -- Um ponto de salvamento da transação para que mais tarde você possa efetuar um ROLLBACK, caso necessário
    - ROLLBACK -- Restaura banco de dados ao original desde o último commit.
